apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-localapp-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium-retain
  resources:
    requests:
      storage: 10Gi
